# Array(数组)
* rank  --数组的维度，一维数组的rank == 1，二维数组的rank == 2......

In [14]:
import numpy as np

In [18]:
arrs = np.array([1, 2, 3, 4])

In [24]:
arrs

array([1, 2, 3, 4])

In [25]:
type(arrs)

numpy.ndarray

In [26]:
arrs.shape

(4,)

* -1类似拆包中的*，就是占据剩余的所有长度

In [38]:
arrs = arrs.reshape(1, -1)

In [39]:
arrs.shape

(1, 4)

In [35]:
arrs = arrs.reshape(-1, 1)

In [36]:
arrs.shape

(4, 1)

In [40]:
arrs = arrs.reshape(2, -1)

In [79]:
arrs.shape

(2, 2)

In [42]:
arrs

array([[1, 2],
       [3, 4]])

In [43]:
arrs[1][0] = 30

In [44]:
arrs

array([[ 1,  2],
       [30,  4]])

* zeros 创建元素为0的数组

In [47]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

* ones 创建元素为1的数组

In [48]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

* full 创建自定义元素的数组

In [57]:
np.full((2, 3), 0)

array([[0, 0, 0],
       [0, 0, 0]])

* eye 创建一个二维的线性矩阵

In [61]:
np.eye(6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

* random.random 创建一个随机的数组，取值范围(0-1)

In [76]:
np.random.random((3, 4))

array([[ 0.6450364 ,  0.83466238,  0.76878571,  0.75315301],
       [ 0.48486547,  0.11008607,  0.32907767,  0.64976839],
       [ 0.86327805,  0.3214463 ,  0.31826037,  0.0093988 ]])

# indexing